# Generated by Django 5.0 on 2023-12-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceEntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="What is the name of this entity type?",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service entity type",
                "verbose_name_plural": "Service entity types",
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ServiceEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What is the name of this entity?",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="What kind of entity is this?",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_entities",
                        to="cat_ca.serviceentitytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service entity",
                "verbose_name_plural": "Service entities",
                "ordering": ["type", "name"],
                "base_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["type", "name"],
                        name="service_entity_index",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="serviceentity",
            constraint=models.UniqueConstraint(
                fields=("type", "name"),
                name="unique_service_entity",
                violation_error_message="An entity with this type and name already exists.",
            ),
        ),
    ]
